blueprint:
  domain: automation
  name: Moes/Tuya 4-Button Scene Switch with Virtual Layers by Emmaly
  description: Automate your Moes/Tuya 4-Button Scene Switch device via Zigbee with four configurable virtual layers.
  source_url: https://raw.githubusercontent.com/emmaly/homeassistant-blueprints/refs/heads/main/tuya/4button-switch/4button-switch-layered.yaml

  input:
    input_device:
      name: Input Device
      description: Select the Moes/Tuya 4-Button Scene Switch device
      selector:
        device:
          integration: zha

    layer_helper:
      name: Layer Helper
      description: Select the layer number helper dedicated to this switch
      selector:
        entity:
          domain: input_number

    layer_1_button_1_short_action:
      name: Layer 1 - Button 1 - Single Press
      description: Action to run for layer 1, button 1 (top-left), single press
      default: []
      selector:
        action: {}
    layer_1_button_1_double_action:
      name: Layer 1 - Button 1 - Double Press
      description: Action to run for layer 1, button 1 (top-left), double press
      default: []
      selector:
        action: {}
    layer_1_button_2_short_action:
      name: Layer 1 - Button 2 - Single Press
      description: Action to run for layer 1, button 2 (top-right), single press
      default: []
      selector:
        action: {}
    layer_1_button_2_double_action:
      name: Layer 1 - Button 2 - Double Press
      description: Action to run for layer 1, button 2 (top-right), double press
      default: []
      selector:
        action: {}
    layer_1_button_3_short_action:
      name: Layer 1 - Button 3 - Single Press
      description: Action to run for layer 1, button 3 (bottom-left), single press
      default: []
      selector:
        action: {}
    layer_1_button_3_double_action:
      name: Layer 1 - Button 3 - Double Press
      description: Action to run for layer 1, button 3 (bottom-left), double press
      default: []
      selector:
        action: {}
    layer_1_button_4_short_action:
      name: Layer 1 - Button 4 - Single Press
      description: Action to run for layer 1, button 4 (bottom-right), single press
      default: []
      selector:
        action: {}
    layer_1_button_4_double_action:
      name: Layer 1 - Button 4 - Double Press
      description: Action to run for layer 1, button 4 (bottom-right), double press
      default: []
      selector:
        action: {}
    layer_1_activated_action:
      name: Layer 1 Activated
      description: (optional) Action to run when Layer 1 is activated. This does not override the layer switching, but instead can be used as a helpful action, such as turning on a device about to be controlled by this layer.
      default: []
      selector:
        action: {}
    layer_1_deactivated_action:
      name: Layer 1 Deactivated
      description: (optional) Action to run when Layer 1 is deactivated. This does not override the layer switching, but instead can be used as a helpful action, such as turning off a device that was controlled by this layer.
      default: []
      selector:
        action: {}

    layer_2_button_1_short_action:
      name: Layer 2 - Button 1 - Single Press
      description: Action to run for layer 2, button 1 (top-left), single press
      default: []
      selector:
        action: {}
    layer_2_button_1_double_action:
      name: Layer 2 - Button 1 - Double Press
      description: Action to run for layer 2, button 1 (top-left), double press
      default: []
      selector:
        action: {}
    layer_2_button_2_short_action:
      name: Layer 2 - Button 2 - Single Press
      description: Action to run for layer 2, button 2 (top-right), single press
      default: []
      selector:
        action: {}
    layer_2_button_2_double_action:
      name: Layer 2 - Button 2 - Double Press
      description: Action to run for layer 2, button 2 (top-right), double press
      default: []
      selector:
        action: {}
    layer_2_button_3_short_action:
      name: Layer 2 - Button 3 - Single Press
      description: Action to run for layer 2, button 3 (bottom-left), single press
      default: []
      selector:
        action: {}
    layer_2_button_3_double_action:
      name: Layer 2 - Button 3 - Double Press
      description: Action to run for layer 2, button 3 (bottom-left), double press
      default: []
      selector:
        action: {}
    layer_2_button_4_short_action:
      name: Layer 2 - Button 4 - Single Press
      description: Action to run for layer 2, button 4 (bottom-right), single press
      default: []
      selector:
        action: {}
    layer_2_button_4_double_action:
      name: Layer 2 - Button 4 - Double Press
      description: Action to run for layer 2, button 4 (bottom-right), double press
      default: []
      selector:
        action: {}
    layer_2_activated_action:
      name: Layer 2 Activated
      description: (optional) Action to run when Layer 2 is activated. This does not override the layer switching, but instead can be used as a helpful action, such as turning on a device about to be controlled by this layer.
      default: []
      selector:
        action: {}
    layer_2_deactivated_action:
      name: Layer 2 Deactivated
      description: (optional) Action to run when Layer 2 is deactivated. This does not override the layer switching, but instead can be used as a helpful action, such as turning off a device that was controlled by this layer.
      default: []
      selector:
        action: {}

    layer_3_button_1_short_action:
      name: Layer 3 - Button 1 - Single Press
      description: Action to run for layer 3, button 1 (top-left), single press
      default: []
      selector:
        action: {}
    layer_3_button_1_double_action:
      name: Layer 3 - Button 1 - Double Press
      description: Action to run for layer 3, button 1 (top-left), double press
      default: []
      selector:
        action: {}
    layer_3_button_2_short_action:
      name: Layer 3 - Button 2 - Single Press
      description: Action to run for layer 3, button 2 (top-right), single press
      default: []
      selector:
        action: {}
    layer_3_button_2_double_action:
      name: Layer 3 - Button 2 - Double Press
      description: Action to run for layer 3, button 2 (top-right), double press
      default: []
      selector:
        action: {}
    layer_3_button_3_short_action:
      name: Layer 3 - Button 3 - Single Press
      description: Action to run for layer 3, button 3 (bottom-left), single press
      default: []
      selector:
        action: {}
    layer_3_button_3_double_action:
      name: Layer 3 - Button 3 - Double Press
      description: Action to run for layer 3, button 3 (bottom-left), double press
      default: []
      selector:
        action: {}
    layer_3_button_4_short_action:
      name: Layer 3 - Button 4 - Single Press
      description: Action to run for layer 3, button 4 (bottom-right), single press
      default: []
      selector:
        action: {}
    layer_3_button_4_double_action:
      name: Layer 3 - Button 4 - Double Press
      description: Action to run for layer 3, button 4 (bottom-right), double press
      default: []
      selector:
        action: {}
    layer_3_activated_action:
      name: Layer 3 Activated
      description: (optional) Action to run when Layer 3 is activated. This does not override the layer switching, but instead can be used as a helpful action, such as turning on a device about to be controlled by this layer.
      default: []
      selector:
        action: {}
    layer_3_deactivated_action:
      name: Layer 3 Deactivated
      description: (optional) Action to run when Layer 3 is deactivated. This does not override the layer switching, but instead can be used as a helpful action, such as turning off a device that was controlled by this layer.
      default: []
      selector:
        action: {}

    layer_4_button_1_short_action:
      name: Layer 4 - Button 1 - Single Press
      description: Action to run for layer 4, button 1 (top-left), single press
      default: []
      selector:
        action: {}
    layer_4_button_1_double_action:
      name: Layer 4 - Button 1 - Double Press
      description: Action to run for layer 4, button 1 (top-left), double press
      default: []
      selector:
        action: {}
    layer_4_button_2_short_action:
      name: Layer 4 - Button 2 - Single Press
      description: Action to run for layer 4, button 2 (top-right), single press
      default: []
      selector:
        action: {}
    layer_4_button_2_double_action:
      name: Layer 4 - Button 2 - Double Press
      description: Action to run for layer 4, button 2 (top-right), double press
      default: []
      selector:
        action: {}
    layer_4_button_3_short_action:
      name: Layer 4 - Button 3 - Single Press
      description: Action to run for layer 4, button 3 (bottom-left), single press
      default: []
      selector:
        action: {}
    layer_4_button_3_double_action:
      name: Layer 4 - Button 3 - Double Press
      description: Action to run for layer 4, button 3 (bottom-left), double press
      default: []
      selector:
        action: {}
    layer_4_button_4_short_action:
      name: Layer 4 - Button 4 - Single Press
      description: Action to run for layer 4, button 4 (bottom-right), single press
      default: []
      selector:
        action: {}
    layer_4_button_4_double_action:
      name: Layer 4 - Button 4 - Double Press
      description: Action to run for layer 4, button 4 (bottom-right), double press
      default: []
      selector:
        action: {}
    layer_4_activated_action:
      name: Layer 4 Activated
      description: (optional) Action to run when Layer 4 is activated. This does not override the layer switching, but instead can be used as a helpful action, such as turning on a device about to be controlled by this layer.
      default: []
      selector:
        action: {}
    layer_4_deactivated_action:
      name: Layer 4 Deactivated
      description: (optional) Action to run when Layer 4 is deactivated. This does not override the layer switching, but instead can be used as a helpful action, such as turning off a device that was controlled by this layer.
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - id: layer_changed
    trigger: state
    entity_id: !input layer_helper
  - id: button_1_short_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_short_press
    subtype: button_1
  - id: button_1_double_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_double_press
    subtype: button_1
  - id: button_1_long_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_long_press
    subtype: button_1
  - id: button_2_short_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_short_press
    subtype: button_2
  - id: button_2_double_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_double_press
    subtype: button_2
  - id: button_2_long_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_long_press
    subtype: button_2
  - id: button_3_short_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_short_press
    subtype: button_3
  - id: button_3_double_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_double_press
    subtype: button_3
  - id: button_3_long_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_long_press
    subtype: button_3
  - id: button_4_short_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_short_press
    subtype: button_4
  - id: button_4_double_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_double_press
    subtype: button_4
  - id: button_4_long_event
    trigger: device
    domain: zha
    device_id: !input input_device
    type: remote_button_long_press
    subtype: button_4

action:
- variables:
    command: "{{ trigger.id }}"
    current_layer_entity: !input layer_helper
    current_layer: "{{ states(current_layer_entity) | int }}"
    previous_layer: "{{ trigger.from_state.state | int if trigger.from_state is not none else 1 }}"
    layered_command: "layer_{{ current_layer }}_{{ command }}"

# Layer deactivation events
- choose:
  - conditions:
    - "{{ command == 'layer_changed' and previous_layer == 1 }}"
    sequence: !input "layer_1_deactivated_action"
  - conditions:
    - "{{ command == 'layer_changed' and previous_layer == 2 }}"
    sequence: !input "layer_2_deactivated_action"
  - conditions:
    - "{{ command == 'layer_changed' and previous_layer == 3 }}"
    sequence: !input "layer_3_deactivated_action"
  - conditions:
    - "{{ command == 'layer_changed' and previous_layer == 4 }}"
    sequence: !input "layer_4_deactivated_action"

# Layer activation events
- choose:
  - conditions:
    - "{{ command == 'layer_changed' and current_layer == 1 }}"
    sequence: !input "layer_1_activated_action"
  - conditions:
    - "{{ command == 'layer_changed' and current_layer == 2 }}"
    sequence: !input "layer_2_activated_action"
  - conditions:
    - "{{ command == 'layer_changed' and current_layer == 3 }}"
    sequence: !input "layer_3_activated_action"
  - conditions:
    - "{{ command == 'layer_changed' and current_layer == 4 }}"
    sequence: !input "layer_4_activated_action"

# Button events
- choose:

  # Layer selection via long press actions
  - conditions:
    - "{{ command == 'button_1_long_event' }}"
    sequence:
      - service: input_number.set_value
        target:
          entity_id: !input layer_helper
        data:
          value: 1
  - conditions:
    - "{{ command == 'button_2_long_event' }}"
    sequence:
      - service: input_number.set_value
        target:
          entity_id: !input layer_helper
        data:
          value: 2
  - conditions:
    - "{{ command == 'button_3_long_event' }}"
    sequence:
      - service: input_number.set_value
        target:
          entity_id: !input layer_helper
        data:
          value: 3
  - conditions:
    - "{{ command == 'button_4_long_event' }}"
    sequence:
      - service: input_number.set_value
        target:
          entity_id: !input layer_helper
        data:
          value: 4

  # Layer 1 short & double press actions
  - conditions:
    - "{{ layered_command == 'layer_1_button_1_short_event' }}"
    sequence: !input "layer_1_button_1_short_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_1_double_event' }}"
    sequence: !input "layer_1_button_1_double_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_2_short_event' }}"
    sequence: !input "layer_1_button_2_short_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_2_double_event' }}"
    sequence: !input "layer_1_button_2_double_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_3_short_event' }}"
    sequence: !input "layer_1_button_3_short_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_3_double_event' }}"
    sequence: !input "layer_1_button_3_double_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_4_short_event' }}"
    sequence: !input "layer_1_button_4_short_action"
  - conditions:
    - "{{ layered_command == 'layer_1_button_4_double_event' }}"
    sequence: !input "layer_1_button_4_double_action"

  # Layer 2 short & double press actions
  - conditions:
    - "{{ layered_command == 'layer_2_button_1_short_event' }}"
    sequence: !input "layer_2_button_1_short_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_1_double_event' }}"
    sequence: !input "layer_2_button_1_double_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_2_short_event' }}"
    sequence: !input "layer_2_button_2_short_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_2_double_event' }}"
    sequence: !input "layer_2_button_2_double_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_3_short_event' }}"
    sequence: !input "layer_2_button_3_short_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_3_double_event' }}"
    sequence: !input "layer_2_button_3_double_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_4_short_event' }}"
    sequence: !input "layer_2_button_4_short_action"
  - conditions:
    - "{{ layered_command == 'layer_2_button_4_double_event' }}"
    sequence: !input "layer_2_button_4_double_action"

  # Layer 3 short & double press actions
  - conditions:
    - "{{ layered_command == 'layer_3_button_1_short_event' }}"
    sequence: !input "layer_3_button_1_short_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_1_double_event' }}"
    sequence: !input "layer_3_button_1_double_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_2_short_event' }}"
    sequence: !input "layer_3_button_2_short_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_2_double_event' }}"
    sequence: !input "layer_3_button_2_double_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_3_short_event' }}"
    sequence: !input "layer_3_button_3_short_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_3_double_event' }}"
    sequence: !input "layer_3_button_3_double_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_4_short_event' }}"
    sequence: !input "layer_3_button_4_short_action"
  - conditions:
    - "{{ layered_command == 'layer_3_button_4_double_event' }}"
    sequence: !input "layer_3_button_4_double_action"

  # Layer 4 short & double press actions
  - conditions:
    - "{{ layered_command == 'layer_4_button_1_short_event' }}"
    sequence: !input "layer_4_button_1_short_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_1_double_event' }}"
    sequence: !input "layer_4_button_1_double_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_2_short_event' }}"
    sequence: !input "layer_4_button_2_short_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_2_double_event' }}"
    sequence: !input "layer_4_button_2_double_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_3_short_event' }}"
    sequence: !input "layer_4_button_3_short_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_3_double_event' }}"
    sequence: !input "layer_4_button_3_double_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_4_short_event' }}"
    sequence: !input "layer_4_button_4_short_action"
  - conditions:
    - "{{ layered_command == 'layer_4_button_4_double_event' }}"
    sequence: !input "layer_4_button_4_double_action"
